name: End-to-End Tests

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: 🛎️ Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # All history for branches and tags

      - name: 📦 Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: 🛠️ Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: '${{ matrix.node-version }}'
          cache: pnpm

      - name: 📂 Install Dependencies
        run: pnpm i

      - name: 🧐 Check Code Quality
        run: pnpm lint

      # - name: 🎭 Install Playwright
      #   run: pnpm i playwright http-server wait-on; npx playwright install --with-deps

      - name: 💰 Profit
        run: echo 🐞
